# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:29
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160323_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
