# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 08:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160323_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
