# Generated by Django 5.2.9 on 2026-01-01 19:58

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        base_slug = slugify(post.title) or 'post'
        slug = base_slug
        counter = 1
        while Post.objects.filter(slug=slug).exclude(pk=post.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160323_1229'),
    ]

    operations = [
        # Step 1: Add slug field without unique constraint
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, default=''),
        ),
        # Step 2: Generate slugs for existing posts
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
